rvm:
  - 2.0.0

cache:
  directories:
    - $PWD/packer

before_install: wget --no-check-certificate https://s3-us-west-2.amazonaws.com/packerfork/linux/packer-jnprautomate-lin-current.zip && unzip -d packer packer-jnprautomate-lin-current.zip
before_script: export PATH=$PATH:$PWD/packer

script: bundle exec thor packer:validate

notifications:
  email:
    on_success: never
    on_failure: never
