---
# Juniper.net login/password
login: test
password: test
# X46-D20.5
name: 12.1X46-D20.5
filename: junos-vsrx-12.1X46-D20.5-domestic.ova
download: https://s3-us-west-2.amazonaws.com/junos-vsrx/junos-vsrx-12.1X46-D20.5-domestic.ova
ovf: junos-vsrx-12.1X46-D20.5-domestic.ovf
mf: junos-vsrx-12.1X46-D20.5-domestic.mf
# X46-D15.3.b
name: 12.1X46-D15.3.b
filename: junos-vsrx-12.1X46-D15.3.b-domestic.ova
download: https://s3-us-west-2.amazonaws.com/junos-vsrx/junos-vsrx-12.1X46-D15.3.b-domestic.ova
ovf: junos-vsrx-12.1X46-D15.3.b-domestic.ovf
mf: junos-vsrx-12.1X46-D15.3.b-domestic.mf
# X46-D10.2
name: 12.1X46-D10.2
filename: junos-vsrx-12.1X46-D10.2-domestic.ova
download: https://s3-us-west-2.amazonaws.com/junos-vsrx/junos-vsrx-12.1X46-D10.2-domestic.ova
ovf: junos-vsrx-12.1X46-D10.2-domestic.ovf
mf: junos-vsrx-12.1X46-D10.2-domestic.mf
