---
# Juniper.net login/password
login: test
password: test
# X46-D20.5
name: 12.1X46-D20.5
filename: junos-vsrx-12.1X46-D20.5-domestic.ova
ovf: junos-vsrx-12.1X46-D20.5-domestic.ovf
mf: junos-vsrx-12.1X46-D20.5-domestic.mf
# X46-D15.3
name: 12.1X46-D15.3
filename: junos-vsrx-12.1X46-D15.3-domestic.ova
ovf: junos-vsrx-12.1X46-D15.3-domestic.ovf
mf: junos-vsrx-12.1X46-D15.3-domestic.mf
# X46-D10.2
name: 12.1X46-D10.2
filename: junos-vsrx-12.1X46-D10.2-domestic.ova
ovf: junos-vsrx-12.1X46-D10.2-domestic.ovf
mf: junos-vsrx-12.1X46-D10.2-domestic.mf
